version: 0.2
phases:
  install:
    runtime-version:
    java: current
    commands:
      echo "iniciando..."
  build:
    commands:
      echo "deu certo?"
      mvn clean install -DskipTests
  post_build:
    commands:
      echo"Sucesso!"
      